workflow:
  rules:
    # For pushes, MRs, scheduled pipelines
    - when: always

stages:
  - lint
  - build
  - test
  - post

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CUSTOM_CI_IMAGE: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"

.nix_build_template:
  interruptible: true
  tags:
    - native-nix
  before_script:
    - git config --global --add url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/.insteadOf "git@${CI_SERVER_HOST}:"
    - git config --global --add url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/.insteadOf "ssh://git@${CI_SERVER_HOST}/"
    - unset NIX_PATH
  cache:
    key: "${CI_PROJECT_ID}-${CI_PROJECT_NAME}-nix-cache"
    paths:
      - "$CI_PROJECT_DIR/.cache/nix"

.hardware_build_template:
  extends:
    - .nix_build_template
  rules:
    # Resource groups do not work across forks. However, we need the resource
    # group to apply globally for the GitLab CI runner. As a workaround, we
    # only run this job in the main repository (on pull requests). Once all
    # forks were rebased, this change becomes effective.
    - if: '$CI_PROJECT_PATH == "cyberus/cloud/libvirt"'
      when: always
    - when: never
  variables:
    PYTHONUNBUFFERED: "1"
    TERM: "xterm"
    DBG_LOG_DIR: "./logs"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - logs/
  # if you want to use your own before_script create a new before_script block in a real job section
  # a before_script block in a job always overrides this definition - the yaml array is not cumulative
  before_script:
    # setup ssh key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - umask 077
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - cp "$SSH_PRIVATE_KEY" ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - cp "$SSH_PUBLIC_KEY" ~/.ssh/id_ed25519.pub
    - chmod 600 ~/.ssh/id_ed25519.pub
    # generate ssh client configuration file - you dont need all parameters in each ssh commnd line
    - echo 'Host *' > ~/.ssh/config
    - echo "  UserKnownHostsFile ${HOME}/.ssh/known_hosts" >> ~/.ssh/config
    - echo "  User benchmark" >> ${HOME}/.ssh/config
    - echo "  IdentityFile ${HOME}/.ssh/id_ed25519" >> ~/.ssh/config
    - echo "  SendEnv CI_SERVER_PROTOCOL" >> ~/.ssh/config
    - echo "  SendEnv CI_JOB_TOKEN" >> ~/.ssh/config
    - echo "  SendEnv CI_SERVER_HOST" >> ~/.ssh/config
    - echo "  SendEnv CI_COMMIT_REF_NAME" >> ~/.ssh/config
    - echo "  SendEnv CI_PROJECT_NAME" >> ~/.ssh/config
    - echo "  SendEnv CI_PROJECT_PATH" >> ~/.ssh/config
    - echo "  SendEnv CI_PIPELINE_ID" >> ~/.ssh/config
    - echo "  SendEnv CI_MERGE_REQUEST_SOURCE_PROJECT_PATH" >> ~/.ssh/config
    - echo "  SendEnv TESTSUITE" >> ~/.ssh/config
  # if you want to use your own after_script create a new after_script block in a real job section
  # a after_script block in a job always overrides this definition - the yaml array is not cumulative
  after_script:
    - echo "Cleanup all VMs on each host"
    - nix-shell -p openssh --run './local_tests/run_chv_profile_cleanup.sh ${CI_PIPELINE_ID} ${CI_PROJECT_NAME}'
    - echo "Cleanup all working directories on each host"
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-turin "rm -rf tmp-${CI_PIPELINE_ID}"' || true
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-granite-rapids "rm -rf tmp-${CI_PIPELINE_ID}"' || true
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-sapphire-rapids "rm -rf tmp-${CI_PIPELINE_ID}"' || true
    - echo "Clean shared nfs directory"
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-turin "rm -rf /exports/gitlab/${CI_PIPELINE_ID}"' || true

lint:commit:
  stage: lint
  rules:
      # Needed for TARGET_BRANCH below.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never
  extends:
    - .nix_build_template
  variables:
    GIT_DEPTH: "0"  # Ensures full Git history is fetched
  script:
    # Determine the target branch of the merge request
    - TARGET_BRANCH=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-$CI_DEFAULT_BRANCH}
    - echo "TARGET_BRANCH=$TARGET_BRANCH"
    # Lint commit messages in the range from target branch to current HEAD
    - nix run nixpkgs#gitlint -- --commits origin/$TARGET_BRANCH..

lint:nix-fmt:
  stage: lint
  extends:
    - .nix_build_template
  script:
    - nix fmt -- --ci

build:packages:
  stage: build
  rules:
    - when: always
  extends:
    - .nix_build_template
  # No dependency to lint stage.
  dependencies: []
  needs: []
  script:
    - nix build -L .#libvirt
    - nix build -L .#libvirt-debugoptimized

build:meson:
  stage: build
  rules:
    - when: always
  extends:
    - .nix_build_template
  # No dependency to lint stage.
  dependencies: []
  needs: []
  script:
    - nix develop . --command bash -c "meson setup build && meson compile -C build"

build:nixos_tests:
  stage: build
  rules:
    - when: always
  extends:
    - .nix_build_template
  # No dependency to lint stage.
  dependencies: []
  needs: []
  script:
    - nix build -L .#tests.x86_64-linux.all_drivers

.test_nixos_tests:
  stage: test
  rules:
    # Resource groups do not work across forks. However, we need the resource
    # group to apply globally for the GitLab CI runner. As a workaround, we
    # only run this job in the main repository (on pull requests). Once all
    # forks were rebased, this change becomes effective.
    - if: '$CI_PROJECT_PATH == "cyberus/cloud/libvirt"'
      when: always
    - when: never
  extends:
    - .nix_build_template
  variables:
    PYTHONUNBUFFERED: "1"
    TERM: "xterm"
    DBG_LOG_DIR: "./logs"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - logs/
  script:
    # Create a unique tmp directory where the nixos test driver places the VM
    # images. We must ensure to delete those directories, as they are currently
    # not automatically cleaned up after the CI run finishes.
    - TMPDIR=$(mktemp -d)
    - export TMPDIR
    - trap 'rm -rf "$TMPDIR"' EXIT
    - mkdir "${DBG_LOG_DIR}"
    - nix run -L .#tests.x86_64-linux.$TEST_ATTR.passthru.no_port_forwarding.driver 2>&1 | tee "${DBG_LOG_DIR}/nixos_driver.log"

test:default-tests:
  extends:
    - .test_nixos_tests
  variables:
    TEST_ATTR: default

test:live-migration-tests:
  extends:
    - .test_nixos_tests
  variables:
    TEST_ATTR: live_migration

test:version_migration-tests:
  extends:
    - .test_nixos_tests
  variables:
    TEST_ATTR: version_migration

test:hugepage-tests:
  extends:
    - .test_nixos_tests
  variables:
    TEST_ATTR: hugepage

test:numa-host-tests:
  extends:
    - .test_nixos_tests
  variables:
    TEST_ATTR: numa_hosts

# the cpu profile test requires the appropriate hardware
test:cpu_profiles:
  stage: test
  resource_group: ferona-hardware
  extends:
    - .hardware_build_template
  parallel:
    matrix:
      - TESTSUITE: run_cpu_profile_test.sh
        TARGETHOST:
          - ferona-sapphire-rapids
          - ferona-granite-rapids
  script:
    - rm -rf logs && mkdir logs
    - nix-shell -p openssh --run './local_tests/checkout_repo_remote.sh ${TARGETHOST}'
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ${TARGETHOST} "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/${TESTSUITE} tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}"' 2>&1 | tee logs/${TARGETHOST}.log
  after_script:
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ${TARGETHOST} "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/kill_child_pids.sh"' || true
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ${TARGETHOST} "rm -rf tmp-${CI_PIPELINE_ID}"' || true

test:live-migration-bare-metal:
  stage: test
  resource_group: ferona-hardware
  extends:
    - .hardware_build_template
  script:
    - rm -rf logs && mkdir logs
    # checkout repo on each host
    - nix-shell -p openssh --run './local_tests/checkout_repo_remote.sh ferona-turin'
    - nix-shell -p openssh --run './local_tests/checkout_repo_remote.sh ferona-granite-rapids'
    - nix-shell -p openssh --run './local_tests/checkout_repo_remote.sh ferona-sapphire-rapids'
    # prepare image on nfs server host
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-turin "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/run_chv_profile_prepare_images.sh ${CI_PIPELINE_ID}"' 2>&1 | tee -a logs/ferona-turin.log
    # build CHV on each host
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-granite-rapids "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/run_chv_profile_prepare_chv.sh"'
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-sapphire-rapids "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/run_chv_profile_prepare_chv.sh"'
    # build vm and run live migration
    - nix-shell -p openssh --run './local_tests/run_chv_profile_test.sh ${CI_PIPELINE_ID} ${CI_PROJECT_NAME}'

test:live-migration-windows-bare-metal:
  stage: test
  resource_group: ferona-hardware
  extends:
    - .hardware_build_template
  script:
    - rm -rf logs && mkdir logs
    # checkout repo on each host
    - nix-shell -p openssh --run './local_tests/checkout_repo_remote.sh ferona-turin'
    - nix-shell -p openssh --run './local_tests/checkout_repo_remote.sh ferona-granite-rapids'
    - nix-shell -p openssh --run './local_tests/checkout_repo_remote.sh ferona-sapphire-rapids'
    # prepare image on nfs server host
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-turin "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/run_chv_profile_prepare_windows_image.sh ${CI_PIPELINE_ID}"' 2>&1 | tee -a logs/ferona-turin.log
    # build CHV on each host
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-granite-rapids "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/run_chv_profile_prepare_chv.sh"'
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-sapphire-rapids "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/run_chv_profile_prepare_chv.sh"'
    # build vm and run live migration
    - nix-shell -p openssh --run './local_tests/run_chv_profile_test_windows.sh ${CI_PIPELINE_ID} ${CI_PROJECT_NAME}'

test:live-migration-windows-different-versions-bare-metal:
  stage: test
  resource_group: ferona-hardware
  extends:
    - .hardware_build_template
  script:
    - rm -rf logs && mkdir logs
    # checkout repo on each host
    - nix-shell -p openssh --run './local_tests/checkout_repo_remote.sh ferona-turin'
    - nix-shell -p openssh --run './local_tests/checkout_repo_remote.sh ferona-granite-rapids'
    - nix-shell -p openssh --run './local_tests/checkout_repo_remote.sh ferona-sapphire-rapids'
    # prepare image on nfs server host
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-turin "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/run_chv_profile_prepare_windows_image.sh ${CI_PIPELINE_ID}"' 2>&1 | tee -a logs/ferona-turin.log
    # build CHV on each host
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-granite-rapids "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/run_chv_profile_prepare_chv.sh"'
    # build previous version in this host
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-sapphire-rapids "./tmp-${CI_PIPELINE_ID}/${CI_PROJECT_NAME}/local_tests/run_chv_profile_prepare_chv.sh prev"'
    # build vm and run live migration
    - nix-shell -p openssh --run './local_tests/run_chv_profile_test_windows.sh ${CI_PIPELINE_ID} ${CI_PROJECT_NAME}'

# this post job should always run
# the test stage job may run into an error and a pipeline timeout
# then this job removes all leftovers from the previos stage
post:live-migration-bare-metal-cleanup:
  stage: post
  resource_group: ferona-hardware
  extends:
    - .hardware_build_template
  script:
    - echo "Cleanup all VMs on each host"
    - nix-shell -p openssh --run './local_tests/run_chv_profile_cleanup.sh ${CI_PIPELINE_ID} ${CI_PROJECT_NAME}' || true
    - echo "Cleanup all working directories on each host"
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-turin "rm -rf tmp-${CI_PIPELINE_ID}"' || true
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-granite-rapids "rm -rf tmp-${CI_PIPELINE_ID}"' || true
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-sapphire-rapids "rm -rf tmp-${CI_PIPELINE_ID}"' || true
    - echo "Clean shared nfs directory"
    - nix-shell -p openssh --run 'ssh -F ~/.ssh/config ferona-turin "rm -rf /exports/gitlab/${CI_PIPELINE_ID}"' || true
  after_script: []
